# Generated by Django 2.1.4 on 2018-12-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TStat14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=200)),
                ('all', models.IntegerField(default=0)),
                ('i', models.IntegerField(default=0)),
                ('ii', models.IntegerField(default=0)),
                ('iii', models.IntegerField(default=0)),
                ('iv', models.IntegerField(default=0)),
                ('v', models.IntegerField(default=0)),
                ('vi', models.IntegerField(default=0)),
                ('vii', models.IntegerField(default=0)),
                ('viii', models.IntegerField(default=0)),
                ('ix', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('xi', models.IntegerField(default=0)),
                ('xii', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TStat15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=200)),
                ('all', models.IntegerField(default=0)),
                ('i', models.IntegerField(default=0)),
                ('ii', models.IntegerField(default=0)),
                ('iii', models.IntegerField(default=0)),
                ('iv', models.IntegerField(default=0)),
                ('v', models.IntegerField(default=0)),
                ('vi', models.IntegerField(default=0)),
                ('vii', models.IntegerField(default=0)),
                ('viii', models.IntegerField(default=0)),
                ('ix', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('xi', models.IntegerField(default=0)),
                ('xii', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TStat16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=200)),
                ('all', models.IntegerField(default=0)),
                ('i', models.IntegerField(default=0)),
                ('ii', models.IntegerField(default=0)),
                ('iii', models.IntegerField(default=0)),
                ('iv', models.IntegerField(default=0)),
                ('v', models.IntegerField(default=0)),
                ('vi', models.IntegerField(default=0)),
                ('vii', models.IntegerField(default=0)),
                ('viii', models.IntegerField(default=0)),
                ('ix', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('xi', models.IntegerField(default=0)),
                ('xii', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TStat17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=200)),
                ('all', models.IntegerField(default=0)),
                ('i', models.IntegerField(default=0)),
                ('ii', models.IntegerField(default=0)),
                ('iii', models.IntegerField(default=0)),
                ('iv', models.IntegerField(default=0)),
                ('v', models.IntegerField(default=0)),
                ('vi', models.IntegerField(default=0)),
                ('vii', models.IntegerField(default=0)),
                ('viii', models.IntegerField(default=0)),
                ('ix', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('xi', models.IntegerField(default=0)),
                ('xii', models.IntegerField(default=0)),
            ],
        ),
    ]
